name: Homepage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-24.04 

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: composer install
      run: composer install --optimize-autoloader --no-dev --no-progress --no-interaction --prefer-dist

    - name: npm install
      run: npm install

    - name: npm build
      run: npm run build
